CREATE TABLE ROLES (
  ID INTEGER NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  USER_ID VARCHAR(20) NOT NULL,
  IISN CHAR(5) DEFAULT NULL,
  LAST_LOGIN_TIME TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY USER_ID (USER_ID),
  KEY IDX_USERS_USERID (USER_ID)
);

CREATE TABLE USERS_ROLES (
  ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_USER_ROLE_ROLEID (ROLE_ID),
  KEY FK_USER_ROLE_USERID (USER_ID),
  KEY IDX_USERROLE_USERID (USER_ID),
  CONSTRAINT FK_USER_ROLE_ROLEID FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_USER_ROLE_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

